export const FETCH_PRODUCT_LOADING = 'FETCH_PRODUCT_LOADING';
export const FETCH_PRODUCT_SUCESS = 'FETCH_PRODUCT_SUCESS';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';
export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const ADD_DEPOSIT_SETTING = 'ADD_DEPOSIT_SETTING';
